FROM httpd
# with sub directory
#COPY ./public-html/ /usr/local/apache2/htdocs/
# with current directory
COPY "$PWD" /usr/local/apache2/htdocs/
# overwrite config file
#COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf
